name: PR workflow on master branch

on:
  pull_request:
    branches: [ master ]

jobs:
  analyze_formatting:
    name: Analyze PR using Dart latest version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
              
      - name: Install dependencies
        run: dart pub get
        
      - name: Install Pana
        run: dart pub global activate pana

      - name: Analyze package warnings
        run: dart pub publish --dry-run
      
      - name: Run pana
        run: $HOME/.pub-cache/bin/pana .

  run_tests:
    name: Run test on `IsolatedWorker` & `JsIsolatedWorker`
    needs: [analyze_formatting]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v0.0.0
        
      - name: Install dependencies
        run: dart pub get
      
      - name: Run test on VM
        run: dart test test/isolated_worker_test.dart

      - name: Run test on Chrome
        run: dart test test/web --platform chrome
